name: MythicalRaces
version: 1.0.3
description: A mythical races plugin
author: Korbsti
main: me.korbsti.mythicalraces.MythicalRaces
softdepend: [PlaceholderAPI]
api-version: 1.17
commands:
   races: